[package]
name = "rust_serve_simple"
version = "0.1.0"
authors = ["madams <mtadams42@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rouille = "3.0.0"
crossbeam-channel = "0.4.3"
serde_json = "1.0.56"